/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'completed' : IDL.Bool,
  'appointmentType' : IDL.Text,
  'notes' : IDL.Text,
  'providerName' : IDL.Text,
  'dateTime' : IDL.Text,
});
export const DailyCheckin = IDL.Record({
  'date' : IDL.Text,
  'mood' : IDL.Nat,
  'restHours' : IDL.Float64,
  'notes' : IDL.Text,
  'exerciseHours' : IDL.Float64,
  'workHours' : IDL.Float64,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
});
export const Medication = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'frequency' : IDL.Text,
  'timeOfDay' : IDL.Text,
});
export const StepStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const TwelveStepProgress = IDL.Record({
  'status' : StepStatus,
  'lastUpdated' : Time,
  'stepNumber' : IDL.Nat,
  'notes' : IDL.Text,
});
export const HabitCompletion = IDL.Record({
  'date' : IDL.Text,
  'habitName' : IDL.Text,
  'completed' : IDL.Bool,
});
export const MedicationLog = IDL.Record({
  'taken' : IDL.Bool,
  'date' : IDL.Text,
  'medicationId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addOrUpdateAppointment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'addOrUpdateJournalEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'addOrUpdateMedication' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
  'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteMedication' : IDL.Func([IDL.Nat], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllDailyCheckins' : IDL.Func([], [IDL.Vec(DailyCheckin)], ['query']),
  'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getAllMedications' : IDL.Func([], [IDL.Vec(Medication)], ['query']),
  'getAllStepProgress' : IDL.Func([], [IDL.Vec(TwelveStepProgress)], ['query']),
  'getHabitCompletionsForDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HabitCompletion)],
      ['query'],
    ),
  'getMedicationLogsForRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(MedicationLog)],
      ['query'],
    ),
  'logMedication' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
  'saveDailyCheckin' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'saveHabitCompletion' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'saveStepProgress' : IDL.Func([IDL.Nat, StepStatus, IDL.Text], [], []),
  'updateAppointmentCompleted' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'completed' : IDL.Bool,
    'appointmentType' : IDL.Text,
    'notes' : IDL.Text,
    'providerName' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  const DailyCheckin = IDL.Record({
    'date' : IDL.Text,
    'mood' : IDL.Nat,
    'restHours' : IDL.Float64,
    'notes' : IDL.Text,
    'exerciseHours' : IDL.Float64,
    'workHours' : IDL.Float64,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
  });
  const Medication = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'frequency' : IDL.Text,
    'timeOfDay' : IDL.Text,
  });
  const StepStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const TwelveStepProgress = IDL.Record({
    'status' : StepStatus,
    'lastUpdated' : Time,
    'stepNumber' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const HabitCompletion = IDL.Record({
    'date' : IDL.Text,
    'habitName' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const MedicationLog = IDL.Record({
    'taken' : IDL.Bool,
    'date' : IDL.Text,
    'medicationId' : IDL.Nat,
  });
  
  return IDL.Service({
    'addOrUpdateAppointment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'addOrUpdateJournalEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'addOrUpdateMedication' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
    'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteMedication' : IDL.Func([IDL.Nat], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllDailyCheckins' : IDL.Func([], [IDL.Vec(DailyCheckin)], ['query']),
    'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getAllMedications' : IDL.Func([], [IDL.Vec(Medication)], ['query']),
    'getAllStepProgress' : IDL.Func(
        [],
        [IDL.Vec(TwelveStepProgress)],
        ['query'],
      ),
    'getHabitCompletionsForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HabitCompletion)],
        ['query'],
      ),
    'getMedicationLogsForRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(MedicationLog)],
        ['query'],
      ),
    'logMedication' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
    'saveDailyCheckin' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'saveHabitCompletion' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'saveStepProgress' : IDL.Func([IDL.Nat, StepStatus, IDL.Text], [], []),
    'updateAppointmentCompleted' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };