/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'completed' : boolean,
  'appointmentType' : string,
  'notes' : string,
  'providerName' : string,
  'dateTime' : string,
}
export interface DailyCheckin {
  'date' : string,
  'mood' : bigint,
  'restHours' : number,
  'notes' : string,
  'exerciseHours' : number,
  'workHours' : number,
}
export interface HabitCompletion {
  'date' : string,
  'habitName' : string,
  'completed' : boolean,
}
export interface JournalEntry {
  'id' : bigint,
  'content' : string,
  'date' : string,
  'tags' : Array<string>,
}
export interface Medication {
  'id' : bigint,
  'active' : boolean,
  'dosage' : string,
  'name' : string,
  'frequency' : string,
  'timeOfDay' : string,
}
export interface MedicationLog {
  'taken' : boolean,
  'date' : string,
  'medicationId' : bigint,
}
export type StepStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface TwelveStepProgress {
  'status' : StepStatus,
  'lastUpdated' : Time,
  'stepNumber' : bigint,
  'notes' : string,
}
export interface _SERVICE {
  'addOrUpdateAppointment' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    undefined
  >,
  'addOrUpdateJournalEntry' : ActorMethod<
    [bigint, string, string, Array<string>],
    undefined
  >,
  'addOrUpdateMedication' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    undefined
  >,
  'deleteAppointment' : ActorMethod<[bigint], undefined>,
  'deleteJournalEntry' : ActorMethod<[bigint], undefined>,
  'deleteMedication' : ActorMethod<[bigint], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllDailyCheckins' : ActorMethod<[], Array<DailyCheckin>>,
  'getAllJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getAllMedications' : ActorMethod<[], Array<Medication>>,
  'getAllStepProgress' : ActorMethod<[], Array<TwelveStepProgress>>,
  'getHabitCompletionsForDate' : ActorMethod<[string], Array<HabitCompletion>>,
  'getMedicationLogsForRange' : ActorMethod<
    [string, string],
    Array<MedicationLog>
  >,
  'logMedication' : ActorMethod<[string, bigint, boolean], undefined>,
  'saveDailyCheckin' : ActorMethod<
    [string, bigint, number, number, number, string],
    undefined
  >,
  'saveHabitCompletion' : ActorMethod<[string, string, boolean], undefined>,
  'saveStepProgress' : ActorMethod<[bigint, StepStatus, string], undefined>,
  'updateAppointmentCompleted' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];