/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DailyCheckin {
    date: string;
    mood: bigint;
    restHours: number;
    notes: string;
    exerciseHours: number;
    workHours: number;
}
export type Time = bigint;
export interface JournalEntry {
    id: bigint;
    content: string;
    date: string;
    tags: Array<string>;
}
export interface HabitCompletion {
    date: string;
    habitName: string;
    completed: boolean;
}
export interface TwelveStepProgress {
    status: StepStatus;
    lastUpdated: Time;
    stepNumber: bigint;
    notes: string;
}
export interface MedicationLog {
    taken: boolean;
    date: string;
    medicationId: bigint;
}
export interface Appointment {
    id: bigint;
    completed: boolean;
    appointmentType: string;
    notes: string;
    providerName: string;
    dateTime: string;
}
export interface Medication {
    id: bigint;
    active: boolean;
    dosage: string;
    name: string;
    frequency: string;
    timeOfDay: string;
}
export enum StepStatus {
    notStarted = "notStarted",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    addOrUpdateAppointment(id: bigint, providerName: string, appointmentType: string, dateTime: string, notes: string, completed: boolean): Promise<void>;
    addOrUpdateJournalEntry(id: bigint, date: string, content: string, tags: Array<string>): Promise<void>;
    addOrUpdateMedication(id: bigint, name: string, dosage: string, frequency: string, timeOfDay: string, active: boolean): Promise<void>;
    deleteAppointment(id: bigint): Promise<void>;
    deleteJournalEntry(id: bigint): Promise<void>;
    deleteMedication(id: bigint): Promise<void>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllDailyCheckins(): Promise<Array<DailyCheckin>>;
    getAllJournalEntries(): Promise<Array<JournalEntry>>;
    getAllMedications(): Promise<Array<Medication>>;
    getAllStepProgress(): Promise<Array<TwelveStepProgress>>;
    getHabitCompletionsForDate(date: string): Promise<Array<HabitCompletion>>;
    getMedicationLogsForRange(_startDate: string, _endDate: string): Promise<Array<MedicationLog>>;
    logMedication(date: string, medicationId: bigint, taken: boolean): Promise<void>;
    saveDailyCheckin(date: string, mood: bigint, workHours: number, exerciseHours: number, restHours: number, notes: string): Promise<void>;
    saveHabitCompletion(date: string, habitName: string, completed: boolean): Promise<void>;
    saveStepProgress(stepNumber: bigint, status: StepStatus, notes: string): Promise<void>;
    updateAppointmentCompleted(_id: bigint, _completed: boolean): Promise<void>;
}
import type { StepStatus as _StepStatus, Time as _Time, TwelveStepProgress as _TwelveStepProgress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOrUpdateAppointment(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateAppointment(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateAppointment(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addOrUpdateJournalEntry(arg0: bigint, arg1: string, arg2: string, arg3: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateJournalEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateJournalEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addOrUpdateMedication(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateMedication(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateMedication(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteAppointment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteJournalEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async deleteMedication(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedication(arg0);
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return result;
        }
    }
    async getAllDailyCheckins(): Promise<Array<DailyCheckin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDailyCheckins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDailyCheckins();
            return result;
        }
    }
    async getAllJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJournalEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJournalEntries();
            return result;
        }
    }
    async getAllMedications(): Promise<Array<Medication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedications();
            return result;
        }
    }
    async getAllStepProgress(): Promise<Array<TwelveStepProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStepProgress();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStepProgress();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabitCompletionsForDate(arg0: string): Promise<Array<HabitCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabitCompletionsForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabitCompletionsForDate(arg0);
            return result;
        }
    }
    async getMedicationLogsForRange(arg0: string, arg1: string): Promise<Array<MedicationLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicationLogsForRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicationLogsForRange(arg0, arg1);
            return result;
        }
    }
    async logMedication(arg0: string, arg1: bigint, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logMedication(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMedication(arg0, arg1, arg2);
            return result;
        }
    }
    async saveDailyCheckin(arg0: string, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDailyCheckin(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDailyCheckin(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveHabitCompletion(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveHabitCompletion(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveHabitCompletion(arg0, arg1, arg2);
            return result;
        }
    }
    async saveStepProgress(arg0: bigint, arg1: StepStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStepProgress(arg0, to_candid_StepStatus_n6(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStepProgress(arg0, to_candid_StepStatus_n6(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateAppointmentCompleted(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentCompleted(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentCompleted(arg0, arg1);
            return result;
        }
    }
}
function from_candid_StepStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StepStatus): StepStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TwelveStepProgress_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TwelveStepProgress): TwelveStepProgress {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _StepStatus;
    lastUpdated: _Time;
    stepNumber: bigint;
    notes: string;
}): {
    status: StepStatus;
    lastUpdated: Time;
    stepNumber: bigint;
    notes: string;
} {
    return {
        status: from_candid_StepStatus_n4(_uploadFile, _downloadFile, value.status),
        lastUpdated: value.lastUpdated,
        stepNumber: value.stepNumber,
        notes: value.notes
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): StepStatus {
    return "notStarted" in value ? StepStatus.notStarted : "completed" in value ? StepStatus.completed : "inProgress" in value ? StepStatus.inProgress : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TwelveStepProgress>): Array<TwelveStepProgress> {
    return value.map((x)=>from_candid_TwelveStepProgress_n2(_uploadFile, _downloadFile, x));
}
function to_candid_StepStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StepStatus): _StepStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StepStatus): {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == StepStatus.notStarted ? {
        notStarted: null
    } : value == StepStatus.completed ? {
        completed: null
    } : value == StepStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
